{{- if and .Values.ingress.enabled .Values.ingress.forwarder.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graylog-forwarder
  labels:
    {{- include "graylog.labels" . | nindent 4 }}
  {{- with .Values.ingress.forwarder.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.forwarder.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.forwarder.tls }}
  tls:
    {{- range .Values.ingress.forwarder.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.forwarder.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "graylog.service.name" $ }}
                port:
                  name: input-forwarder
          {{- end }}
    {{- end }}
{{- end }}
