apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-forwarder
data:
  GRAYLOG_FORWARDER_SERVER_HOSTNAME: {{ .Values.config.GRAYLOG_FORWARDER_SERVER_HOSTNAME }}
  # GRAYLOG_FORWARDER_GRPC_API_TOKEN: "sevret"
  GRAYLOG_MESSAGE_JOURNAL_MAX_AGE: "12h"
  # GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: "8GB"
  # GRAYLOG_DATA_DIR: "/data/graylog-forwarder/data"
  # GRAYLOG_FORWARDER_API_ENABLED: true
  # GRAYLOG_FORWARDER_API_TCP_BIND_ADDRESS: "0.0.0.0:9001"
  # GRAYLOG_FORWARDER_GRPC_API_TOKEN: "some-token"
  # GRAYLOG_NODE_ID_FILE : "/data/graylog-forwarder/node-id"
  # GRAYLOG_MESSAGE_JOURNAL_DIR : "/data/graylog-forwarder/journal"
