apiVersion: v1
kind: Service
metadata:
  name: graylog-forwarder-first-svc
  labels:
    {{- include "graylog-forwarder.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
  selector:
    {{- include "graylog-forwarder.selectorLabels" . | nindent 4 }}
