{{- if .Values.datanode.podDisruptionBudget.enabled }}
{{- if include "graylog.datanode.replicas" . | int | lt 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "graylog.fullname" . | printf "%s-pdb-datanode" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: graylog-datanode
    {{- include "graylog.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.datanode.podDisruptionBudget.minAvailable | default 3 | int }}
  selector:
    matchLabels:
      app: graylog-datanode
{{- end }}
{{- end }}
