{{- $provider := .Values.provider | default "" }}
{{- if and (empty .Values.global.defaultStorageClass) (hasPrefix "aws" $provider) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "graylog.fullname" . | printf "%s-gp3" }}
  annotations:
    {{- if hasSuffix "-managed-sc" $provider }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  # fsType: ext4
  # encrypted: "true"
  # iops: "3000"
  # throughput: "125"  # MiB/s
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}