{{- $isAWS := .Values.provider | default "" | hasPrefix "aws" }}
{{- if empty .Values.global.defaultStorageClass | and $isAWS }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "graylog.fullname" . | print "%s-gp3" }}
  annotations:
    {{- if hasSuffix "-managed-sc" | and $isAWS }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  # fsType: ext4
  # encrypted: "true"
  # iops: "3000"
  # throughput: "125"  # MiB/s
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{- end }}