{{ if .Values.graylog.enabled  }}
## Graylog App StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graylog.fullname" . }}
  labels:
    app: graylog-app
    {{- include "graylog.labels" . | nindent 4 }}
  annotations:
    {{- include "graylog.annotations" . | nindent 4 }}
spec:
  replicas: {{ include "graylog.replicas" . | default 2 | int }}
  serviceName: {{ include "graylog.service.name" . }}
  selector:
    matchLabels:
      app: graylog-app
      {{- include "graylog.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.graylog.updateStrategy.type | default "RollingUpdate" | quote }}
    {{- if .Values.graylog.updateStrategy.type | default "RollingUpdate" | eq "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.graylog.updateStrategy.rollingUpdate.maxUnavailable | default "1" | quote }}
      {{- with .Values.graylog.updateStrategy.rollingUpdate.partition }}
      partition: {{ int . }}
      {{- end }}
    {{- end }}
  template:
    metadata:
      labels:
        app: graylog-app
        {{- include "graylog.selectorLabels" . | nindent 8 }}
      annotations:
        {{- $dd := randAlphaNum 5 | dict "data" }}
        {{- $config := include "graylog.configmap.name" . | lookup "v1" "ConfigMap" .Release.Namespace | default $dd  }}
        {{- $_ := randAlphaNum 5 | set $dd "data" }}
        {{- $secret := include "graylog.secretsName" . | lookup "v1" "Secret" .Release.Namespace | default $dd  }}
        checksum/config: {{ $config.data | quote | sha256sum }}
        checksum/secret: {{ $secret.data | quote | sha256sum }}
      {{- with .Values.graylog.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      dnsPolicy: ClusterFirst
      {{- with .Values.graylog.image.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.graylog.nodeSelector }}
      nodeSelector: {{ .Values.graylog.nodeSelector }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "graylog.serviceAccountName" . }}
      {{- end }}
      securityContext:
        runAsUser: 1100
        runAsGroup: 1100
        fsGroup: 1100
      initContainers:
        - name: copy-data
          image: {{ include "graylog.image" . }}
          imagePullPolicy: {{ .Values.graylog.image.imagePullPolicy }}
          command: [ "/bin/sh", "/scripts/init-script.sh" ]
          env:
            - name: INIT_GRAYLOG_PLUGIN_URLS
              value: {{ include "graylog.plugin.URLs" . | default "" }}
            - name: INIT_GRAYLOG_GEO_MMDB_URLS
              value: {{ include "graylog.mmdb.URLs" . | default "" }}
          envFrom:
            - configMapRef:
                name: {{ include "graylog.configmap.name" . }}
            - secretRef:
                name: {{ include "graylog.secretsName" . }}
          volumeMounts:
            - name: {{ include "graylog.volume.name" . }}
              mountPath: /mnt/data
            - name: init-script
              mountPath: /scripts
            {{- if .Values.graylog.config.tls.enabled }}
            - name: tls-creds
              mountPath: /mnt/tls/tls.crt
              subPath: tls.crt
              readOnly: true
            {{- end }}
        {{- if .Values.graylog.config.plugins.enabled }}
            - name: init-plugins
              mountPath: /mnt/plugins
            {{- range .Values.graylog.plugins }}
            {{- if empty .image | and .existingClaim }}
            - name: {{ .name }}
              mountPath: {{ printf "/mnt/shared/plugins/%s" .name }}
            {{- end }}
            {{- end }}
        {{- range .Values.graylog.plugins }}
        {{- if empty .existingClaim | and .image }}
        - name: {{ printf "copy-plugin-%s" .name }}
          image: {{ .image }}
          command: [ "/bin/sh", "-c", "cp *.jar /mnt/plugins/" ]
          volumeMounts:
            - name: init-plugins
              mountPath: /mnt/plugins
        {{- end }}
        {{- end }}
        {{- end }}
      containers:
        - name: graylog-app
          image: {{ include "graylog.image" . }}
          imagePullPolicy: {{ .Values.graylog.image.imagePullPolicy }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GRAYLOG_HTTP_PUBLISH_URI
              value: {{ include "graylog.publishUri" . | quote }}
          {{- if or .Values.graylog.env .Values.graylog.extraEnv }}
            {{- include "graylog.env" .Values.graylog | indent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "graylog.configmap.name" . }}
            - secretRef:
                name: {{ include "graylog.secretsName" . }}
          ports:
            - name: app
              containerPort: {{ .Values.graylog.service.ports.app | int }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.graylog.service.ports.metrics | int }}
              protocol: TCP
            {{- range .Values.graylog.inputs }}
            - name: {{ .name }}
              containerPort: {{ .targetPort | default .port | int }}
              protocol: {{ .protocol }}
            {{- end }}
            - name: input-fwd-conf
              containerPort: 13302
              protocol: TCP
          {{- if .Values.graylog.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.graylog.service.ports.app | int }}
            initialDelaySeconds: {{ .Values.graylog.livenessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .Values.graylog.livenessProbe.periodSeconds | int }}
            timeoutSeconds: {{ .Values.graylog.livenessProbe.timeoutSeconds | int }}
            failureThreshold: {{ .Values.graylog.livenessProbe.failureThreshold | int }}
            successThreshold: {{ .Values.graylog.livenessProbe.successThreshold |int }}
          {{- end }}
          {{- if .Values.graylog.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.graylog.service.ports.app | int }}
            initialDelaySeconds: {{ .Values.graylog.readinessProbe.initialDelaySeconds | int }}
            periodSeconds: {{ .Values.graylog.readinessProbe.periodSeconds | int }}
            timeoutSeconds: {{ .Values.graylog.readinessProbe.timeoutSeconds | int }}
            failureThreshold: {{ .Values.graylog.readinessProbe.failureThreshold | int }}
            successThreshold: {{ .Values.graylog.readinessProbe.successThreshold | int }}
          {{- end }}
          {{- with .Values.graylog.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "graylog.volume.name" . }}
              mountPath: /usr/share/graylog/data
            {{- if .Values.graylog.config.tls.enabled }}
            - name: tls-creds
              mountPath: /usr/share/graylog/tls
            {{- end }}
            {{- if .Values.graylog.config.plugins.enabled }}
            - name: init-plugins
              mountPath: /usr/share/graylog/plugin
            {{- end }}
      tolerations:
      {{- with .Values.graylog.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with .Values.graylog.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: init-script
        configMap:
          name: init-script-cm
          defaultMode: 0755
      {{- if .Values.graylog.config.tls.enabled }}
      - name: tls-creds
        secret:
          secretName: {{ .Values.graylog.config.tls.secretName | quote }}
      {{- end }}
      {{- if .Values.graylog.config.plugins.enabled }}
      - name: init-plugins
        emptyDir: {}
      {{- range .Values.graylog.plugins }}
      {{- if empty .url | and .existingClaim }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaim }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if not .Values.graylog.persistence.enabled | or .Values.graylog.persistence.existingClaim }}
      - name: {{ include "graylog.volume.name" . }}
        {{- if .Values.graylog.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.graylog.persistence.existingClaim }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- end }}
  {{- if not .Values.graylog.persistence.existingClaim | and .Values.graylog.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ include "graylog.volume.name" . }}
        {{- with .Values.graylog.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.graylog.persistence.labels }}
        labels:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      spec:
        {{- if or .Values.graylog.persistence.storageClass .Values.global.defaultStorageClass }}
        storageClassName: {{ .Values.graylog.persistence.storageClass | default .Values.global.defaultStorageClass }}
        {{- end }}
        accessModes:
        {{- if .Values.graylog.persistence.accessModes }}
        {{- range .Values.graylog.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        {{- else }}
          - "ReadWriteOnce"
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.graylog.persistence.size | default "8Gi" | quote }}
  {{- end }}
{{- end }}
