apiVersion: v2
name: graylog
description: Official Graylog Helm chart for Kubernetes
icon: "https://raw.githubusercontent.com/Graylog2/graylog2-server/refs/tags/7.0.0/graylog2-web-interface/public/images/favicon.png"
type: application
home: https://graylog.org
sources:
  - https://github.com/graylog2
keywords:
  - SIEM
  - API
  - Triage
  - Security
  - Observability
  - Search
  - Logs
  - Monitoring
  - Troubleshooting
  - Events
  - Alerts
annotations:
  artifacthub.io/category: security
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: "graylog"
      image: "graylog/graylog:7.0"
      whitelisted: true
      platforms:
        - linux/amd64
        - linux/arm64
    - name: "graylog-datanode"
      image: "graylog/graylog-datanode:7.0"
      whitelisted: true
      platforms:
        - linux/amd64
        - linux/arm64
  # Changelog
  artifacthub.io/changes: |
    - kind: added
      description: "add LICENSE"
      links:
        - name: "Create LICENSE"
          url: "https://github.com/Graylog2/graylog-helm/pull/59"
    - kind: added
      description: "Support for official MongoDB Kubernetes Operator"
      links:
        - name: "Replace bitnami/mongodb dependency"
          url: "https://github.com/Graylog2/graylog-helm/issues/48"
        - name: "Use MongoDB Kubernetes Operator"
          url: "https://github.com/Graylog2/graylog-helm/pull/55"
    - kind: changed
      description: "Bump appVersion to '7.0'"
    - kind: fixed
      description: "Forwarder ingress TLS condition"
      links:
        - name: "fix: forwarder TLS condition"
          url: "https://github.com/Graylog2/graylog-helm/pull/60"
    - kind: removed
      description: "Remove global size preset value"
      links:
        - name: "Remove global size preset"
          url: "https://github.com/Graylog2/graylog-helm/pull/56"
  artifacthub.io/containsSecurityUpdates: "true"
# This is the chart version.
version: 1.0.0
# This is the version number of the Graylog application bundled with this chart.
appVersion: "7.0"