apiVersion: v2
name: graylog
description: Official Graylog Helm chart for Kubernetes
type: application

# Dependency subcharts
dependencies:
  - name: mongodb
    version: "16.5.21"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.subchart.enabled

# This is the chart version.
version: 0.1.0

# This is the version number of the Graylog application bundled with this chart.
appVersion: "6.3"
