name: Release

on:
  push:
    branches: ["main"]
    paths:
      - graylog/Chart.yaml
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Update Helm dependencies
        run: helm repo add mongodb https://charts.bitnami.com/bitnami && helm repo update
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#  push:
#    runs-on: ubuntu-latest
#    needs: release
#    steps:
#      - name: Get chart from latest release
#        uses: robinraju/release-downloader@v1
#        with:
#          token: "${{ secrets.GITHUB_TOKEN }}"
#          latest: true
#          fileName: 'graylog-*.tgz'
#      - name: Set chart filename
#        id: chart
#        run: echo "chart_filename=$(ls graylog-*.tgz)" >> "$GITHUB_ENV"
#      - name: Push to CloudSmith
#        uses: cloudsmith-io/action@v0.6.13
#        with:
#          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
#          command: "push"
#          format: "helm"
#          owner: "cloudsmith"
#          repo: "grayloginc"
#          file: "${{ env.chart_filename }}"
